# Workflow to run the checkChords script
#
# The script checks the availability of chords from chords.json
# and display the pages not available anymore
#
# TODO:
# - Upload the results as artifacts
# - Find a good way to display the history of results in a page

name: Check chords.json for dead links

on:
    workflow_dispatch:
    schedule:
        # 00:10 every days
        - cron: '15 0 * * *'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Cache node and npm
              uses: actions/setup-node@v4
              with:
                  node-version: 18
                  cache: 'npm'
            - name: Cache node modules
              id: cache-nodemodules
              uses: actions/cache@v3
              env:
                  cache-name: cache-node-modules
              with:
                  # caching node_modules
                  path: node_modules
                  key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-build-${{ env.cache-name }}-
                      ${{ runner.os }}-build-
                      ${{ runner.os }}-
            - name: Install Dependencies
              if: steps.cache-nodemodules.outputs.cache-hit != 'true'
              run: npm ci
            - name: Install and Build
              run: |
                  npm install
                  npm run build
              env:
                  ENV: prod
                  OCTOKIT_PAT: ${{ secrets.OCTOKIT_PAT }}
            - name: Do checks
              run: npm run checkChords
            - uses: actions/upload-artifact@v3
              with:
                  name: check_chords_results
                  path: ./check_chords_results.json
